[[news]]
date = "2026-09"
content = "One paper accepted by IEEE BIBM 2026 (CCF B) 🎉"

[[news]]
date = "2026-09"
content = "Admitted to the Master's program in Artificial Intelligence at Wuhan University 🎉"

[[news]]
date = "2025-10"
content = "Led a team to win the National Silver Award in the China International College Students' Innovation Competition 🏆"

[[news]]
date = "2025-06"
content = "One paper accepted by MICCAI 2025 (CCF B) 🎉"

[[news]]
date = "2025-01"
content = "Meritorious Winner (Top 6%) in the Mathematical Contest in Modeling 🏆"
