[[news]]
date = "2026-09"
content = "一篇论文被 IEEE BIBM 2026 接收（CCF B）🎉"

[[news]]
date = "2026-09"
content = "成功保研至武汉大学人工智能专业 🎉"

[[news]]
date = "2025-10"
content = "带领团队在中国国际大学生创新大赛中获得国家级银奖 🏆"

[[news]]
date = "2025-06"
content = "一篇论文被 MICCAI 2025 接收（CCF B）🎉"

[[news]]
date = "2025-01"
content = "美国大学生数学建模竞赛 Meritorious Winner（前 6%）🏆"
